### ISSUE TITLE
System Design of the app

### ISSUE THREAD

**Issue by juanzenn** [juanzenn/zeus#1]
# System Design
This issue is to track the system design for the basic implementation of Zeus. 

## Application Flow
Here, we have the basic implementation of the flow. We are working with a SQL database (PostgreSQL) and Prisma. One of the key features is to **watch results live** and **share polls with users to answer**.

![app-flow-v2](https://github.com/juanzenn/zeus/assets/31358977/9ae1a489-d55e-4368-ab9e-959544e52c3b)

**Comment by yonnyviz** [comment]
Regarding authentication and user registration, I noticed that you are planning to use the following library for validating sessions: [NextAuth.js](https://next-auth.js.org/getting-started/introduction). Is that correct?

Another question is whether you plan to use Vercel's PostgreSQL serverless service (https://vercel.com/docs/storage/vercel-postgres) to provision the database. Calculating billing costs is essential to keep in mind, as I am unsure if they offer any kind of free tier.

**Comment by juanzenn** [comment]
@yonnyviz Yes, I'm planning on using NextAuth and it's currently working with GitHub Auth. The database is provided by [Neon](https://neon.tech/), currently in the free tier.
