### ISSUE TITLE
Extend README.md with more useful information

### ISSUE THREAD

**Issue by pedrouzcategui** [juanzenn/zeus#2]
I'm having some issues trying to get the project to work initially with the commands in the README.md

I was able to make it run by figuring out some couple of things myself, but I would suggest the following:

1. Include help links for setting up OAuth client for Github: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app

2. Include sample string for the DB connection: https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/connect-your-database-typescript-postgresql

```env
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/zeus"
DIRECT_URL="postgresql://postgres:postgres@localhost:5432/zeus"
```

3. Make sure OAuth and DB are setup before running any playwright tests

**Comment by juanzenn** [comment]
As requested, now the `.env.example` has extra information for setting up the project. 

As for the OAuth and DB setup for Playwright, I couldn't figure that out yet. Feel free to open a new PR with the configuration.

**Comment by pedrouzcategui** [comment]
Thank you @juanzenn !
