### ISSUE TITLE
Add toggle for Pie Chart / Bar Chart on results page

### ISSUE THREAD

**Issue by juanzenn** [juanzenn/zeus#4]
We are currently displaying a bar chart on the results page. We need a switch toggle for pie charts. 

![image](https://github.com/juanzenn/zeus/assets/31358977/f6e7a9bf-c359-489e-8561-6c412f2e200c)

**Comment by Shouvik11-b** [comment]
Hi, I would like to work on this issue, can you assign it to me?

**Comment by juanzenn** [comment]
@Shouvik11-b hey, sure! I'll create the branch, any questions you might have let me know

**Comment by Shouvik11-b** [comment]
Hey Juanzenn
I need a one or two days for the changes
It will be done within that time.
Please don't remove the assigne from me.

**Comment by Shouvik11-b** [comment]
Hey @juanzenn 
These are the screenshots of the product .
![Screenshot (1585)](https://github.com/juanzenn/zeus/assets/81455826/867ce5e6-67e2-4fda-b255-42a0b49692bc)

![Screenshot (1584)](https://github.com/juanzenn/zeus/assets/81455826/de76c348-9391-4ac6-8e38-4d1aa40d46cf)

should I move on to push the changes?

**Comment by juanzenn** [comment]
> Hey @juanzenn 
> These are the screenshots of the product .
> ![Screenshot (1585)](https://github.com/juanzenn/zeus/assets/81455826/867ce5e6-67e2-4fda-b255-42a0b49692bc)
> 
> ![Screenshot (1584)](https://github.com/juanzenn/zeus/assets/81455826/de76c348-9391-4ac6-8e38-4d1aa40d46cf)
> 
> should I move on to push the changes?
> 
> 

You can push it on your own branch and create a pull request. I'll take a look at the code and give you my feedback there.
